apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: engine-api
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.containerPort | quote}}
    prometheus.io/path: '/metrics'
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: engine-api
      version: v1
  template:
    metadata:
      labels:
        app: engine-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.containerPort | quote}}
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: dvdhinesh/engine-api
        imagePullPolicy: Always
        name: engine-api
        ports:
        - containerPort: {{ .Values.containerPort }}
