apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-destinationrule
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-svc
  subsets:
  - name: v1
    labels:
      version: v1